zones:
  12345678: # site1 banner 728x90
    - 1
    - 2
  23456789: # site1 banner 250x250
    - 1
    - 3
banners:
  1:
    image: images/test.png
    url: www.pronostic-facile.fr
  2:
    image: images/test2.png
    url: www.turfistar.com
  3:
    image: images/test3.png
    url: www.gazette-turf.fr

